### ISSUE TITLE
Request of a dependency is an expression

### ISSUE THREAD

**Issue by stabback** [keybase/node-nacl#5]
Hey there!

There's some funky code in `lib/main.js`:

```js
  sodium_mod = "sod" + "ium";

  try {
    nacl_c = require(sodium_mod).api;
  } catch (_error) {
    e = _error;
  }
```

This causes webpack to throw a warning, which some users of kbpgp are experiencing (https://github.com/keybase/kbpgp/issues/157).

Could this be updated to just require "sodium"?  It will make the lib more webpack friendly.

**Comment by maxtaco** [comment]
I think we needed this hack to get around browserify including the module.

**Comment by maxtaco** [comment]
Should be fixed, reopen if not.

**Comment by stabback** [comment]
@maxtaco Thanks for taking a look!  Unfortunately since `sodium` is saved as a `devDependency`, npm / yarn will not install it, leading webpack to still throw errors 😞 .

```
This dependency was not found:

* sodium in ./node_modules/keybase-nacl/lib/main.js

To install it, you can run: npm install --save sodium
```

Should I open a new issue, or can this one be re-opened?

**Comment by maxtaco** [comment]
I'm not a webpack user, so what is the right approach?  The idea is that we should fallback to `tweetnacl` if we don't have `sodium` installed. And in fact, you can only run `sodium` on desktop node, it won't work in the browser.

**Comment by stabback** [comment]
@maxtaco Sorry for the delay in the response!

I do not think there is a straightforward solution here, as the following three are incompatible (according to my understanding of Webpack): 
- The goal of this package is to use node's sodium if it is installed, and tweet-nacl otherwise.
- Webpack throws a warning if a package is required that is not in `dependencies`
- Installing sodium as a dependency breaks browsers

Unfortunately this warning makes the `kbpgp` library unusable with Webpack unless the user is OK with the warnings.  It may be worth adding a note to the README's.

**Comment by maxtaco** [comment]
What a conundrum!  Well, we're willing to accept PRs, however you think we should go.

**Comment by stabback** [comment]
http://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html

I think this is the best bet - mark it as optional and try catch.  Will PR if this seems reasonable!

**Comment by maxtaco** [comment]
yes, great!
